version: '3'
services:
  server:
    build: ./server
    ports:
      - "50051:50051"
  envoy:
    image: envoyproxy/envoy:v1.30-latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    depends_on:
      - server
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - envoy